name: homelab-ops-stack

services:

  # nginx:
  #   image: docker.io/nginx:1.27.0
  #   container_name: homelab-nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   # env_file:
  #   #   - ../base.env
  #   volumes:
  #     - ./nginx/public:/usr/share/nginx/html:rw
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/certificate/:/etc/certificate/:rw
  #   networks:
  #     - network-reverse-proxy

  # https://docs.portainer.io/start/install-ce/server/docker/linux
  # https://github.com/portainer/portainer/issues/6117
  portainer:
    image: docker.io/portainer/portainer-ce:2.20.3
    container_name: homelab-portainer
    restart: always
    ports:
      - 9443:9443
    privileged: true
    # env_file:
    #   - ../base.env
    volumes:
      - /srv/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - network-reverse-proxy

  # Initial Setup: username=admin, password=admin
  # https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/gitlab/#configure-gitlab-authentication-client-using-the-grafana-configuration-file
  grafana:
    image: docker.io/grafana/grafana
    container_name: homelab-grafana
    restart: always
    # env_file:
    #   - ../base.env
    environment:
      GF_SERVER_ROOT_URL: http://192.168.11.2/grafana/
      # GF_SERVER_ROOT_URL: http://localhost/grafana/
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_USERS_DEFAULT_THEME: light
      DS_PROMETHEUS: homelab-prometheus
      GF_AUTH_GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GF_AUTH_GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      GF_AUTH_GITLAB_ENABLED: true
      GF_AUTH_GITLAB_USE_REFRESH_TOKEN: true
      GF_AUTH_GITLAB_AUTH_URL: ${GITLAB_HOST}/oauth/authorize
      GF_AUTH_GITLAB_TOKEN_URL: ${GITLAB_HOST}/oauth/token
      GF_AUTH_GITLAB_API_URL: ${GITLAB_HOST}/api/v4
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - network-reverse-proxy
      - network-grafana
    depends_on:
      - prometheus

  prometheus:
    image: docker.io/prom/prometheus
    container_name: homelab-prometheus
    restart: always
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    # env_file:
    #   - ../base.env
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - volume-prometheus:/prometheus
    networks:
      - network-grafana
      - network-prometheus
    depends_on:
      - nginx-exporter
      - node-exporter
      - cadvisor

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: homelab-nginx-exporter
    restart: always
    command:
      - --nginx.scrape-uri=http://homelab-nginx:8080/stub_status
    # env_file:
    #   - ../base.env
    networks:
      - network-prometheus
      - network-reverse-proxy

  node-exporter:
    image: docker.io/prom/node-exporter:latest
    container_name: homelab-node-exporter
    restart: always
    command:
      - "--path.rootfs=/host"
    # env_file:
    #   - ../base.env
    volumes:
      - /:/host:ro,rslave
    networks:
      - network-prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: homelab-cadvisor
    privileged: true
    # env_file:
    #   - ../base.env
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - network-prometheus

networks:
  network-reverse-proxy:
    name: homelab-network-reverse-proxy
    driver: bridge
  network-grafana:
    name: homelab-network-grafana
  network-prometheus:
    name: homelab-network-prometheus

volumes:
  volume-prometheus:
    name: homelab-volume-prometheus
